name: Daily AI Research Digest

on:
  schedule:
    # Run every day at 9:00 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  send-digest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser python-dotenv
    
    - name: Create .env file
      run: |
        echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
        echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
        echo "RECIPIENT_EMAIL=${{ secrets.RECIPIENT_EMAIL }}" >> .env
    
    - name: Run digest agent
      run: |
        python main.py
    
    - name: Upload logs (if needed)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: digest-logs
        path: digest_agent.log
        retention-days: 7
